package com.figma.sync;

import groovy.json.JsonOutput;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;

import java.io.File;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Gradle Task: syncFigmaTokens
 *
 * Fetches Figma design tokens (color variables) via the Variables REST API,
 * resolves alias chains, and outputs:
 *   - res/values/figma_colors.xml (Android color resources)
 *   - src/main/assets/token_bindings.json (icon→token mapping, if extractTokens enabled)
 */
public abstract class SyncTokensTask extends DefaultTask {

    @Input
    public abstract Property<String> getToken();

    @Input
    public abstract Property<String> getFileKey();

    @Input
    @Optional
    public abstract Property<Boolean> getExtractTokens();

    @Input
    @Optional
    public abstract Property<String> getOutput();

    @OutputFile
    public abstract RegularFileProperty getColorsXmlFile();

    @OutputFile
    @Optional
    public abstract RegularFileProperty getBindingsJsonFile();

    @TaskAction
    public void sync() throws Exception {
        String token = getToken().get();
        String fileKey = getFileKey().get();
        boolean extractTokens = getExtractTokens().getOrElse(false);

        getLogger().lifecycle("[Figma] Fetching design tokens (variables/local) ...");

        // ── Fetch all local variables ────────────────────────────
        Map<String, TokenClient.VariableInfo> variables =
            TokenClient.fetchLocalVariables(token, fileKey);

        getLogger().lifecycle("[Figma] Found {} variables ({} color, {} other)",
            variables.size(),
            variables.values().stream().filter(v -> v.colorHex != null).count(),
            variables.values().stream().filter(v -> v.colorHex == null).count());

        // ── Generate colors.xml ──────────────────────────────────
        File colorsFile = getColorsXmlFile().get().getAsFile();
        colorsFile.getParentFile().mkdirs();
        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.append("<!-- Auto-generated by figma-sync-plugin. DO NOT EDIT. -->\n");
        xml.append("<resources>\n");

        int colorCount = 0;
        for (TokenClient.VariableInfo var : variables.values()) {
            if (var.colorHex == null) continue;
            String resName = "figma_" + sanitizeResName(var.name);
            xml.append("    <color name=\"").append(resName).append("\">")
               .append(var.colorHex).append("</color>\n");
            colorCount++;
        }
        xml.append("</resources>\n");

        java.nio.file.Files.write(colorsFile.toPath(),
            xml.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));
        getLogger().lifecycle("[Figma] Wrote {} colors → {}", colorCount, colorsFile.getPath());

        // ── Generate token_bindings.json ─────────────────────────
        File bindingsFile = getBindingsJsonFile().getOrNull() != null
            ? getBindingsJsonFile().get().getAsFile() : null;

        if (bindingsFile != null && extractTokens) {
            bindingsFile.getParentFile().mkdirs();
            // For now: export all color variables. Icon-level bindings
            // will be added in TokenBindingExtractor (next iteration).
            List<Map<String, Object>> tokenList = new ArrayList<>();
            for (TokenClient.VariableInfo var : variables.values()) {
                if (var.colorHex == null) continue;
                Map<String, Object> entry = new LinkedHashMap<>();
                entry.put("name", var.name);
                entry.put("varId", var.id);
                entry.put("color", var.colorHex);
                tokenList.add(entry);
            }
            Map<String, Object> root = new LinkedHashMap<>();
            root.put("source", "figma_variables_api");
            root.put("count", tokenList.size());
            root.put("tokens", tokenList);

            java.nio.file.Files.write(bindingsFile.toPath(),
                JsonOutput.toJson(root).getBytes(java.nio.charset.StandardCharsets.UTF_8));
            getLogger().lifecycle("[Figma] Wrote token bindings → {}", bindingsFile.getPath());
        }
    }

    static String sanitizeResName(String name) {
        return name.toLowerCase()
            .replaceAll("[^a-z0-9_]", "_")
            .replaceAll("_+", "_")
            .replaceAll("^_|_$", "");
    }
}
