package com.figma.sync;

import groovy.json.JsonOutput;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.ListProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;

import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Gradle Task: syncFigmaTokens
 *
 * Fetches Figma design tokens (color variables) via the Variables REST API,
 * resolves alias chains, and outputs:
 *   - res/values/figma_colors.xml (Android color resources)
 *   - src/main/assets/token_bindings.json (icon→token mapping, if extractTokens enabled)
 *
 * Supports token chain download: when chainDownload=true and collections are specified,
 * only variables in the declared collections + their transitive alias dependencies are fetched.
 */
public abstract class SyncTokensTask extends DefaultTask {

    @Input
    public abstract Property<String> getToken();

    @Input
    public abstract Property<String> getFileKey();

    @Input
    @Optional
    public abstract Property<Boolean> getExtractTokens();

    @Input
    @Optional
    public abstract Property<String> getOutput();

    /** Enable token chain download (transitive alias resolution). */
    @Input
    @Optional
    public abstract Property<Boolean> getChainDownload();

    /** Variable collection names to include. Empty = all collections. */
    @Input
    @Optional
    public abstract ListProperty<String> getCollections();

    /** Data source mode: "rest_api" (default) or "plugin" (reads figma_plugin_export.json). */
    @Input
    @Optional
    public abstract Property<String> getTokenSource();

    /** Path to the Figma plugin export JSON (used when tokenSource = "plugin"). */
    @Input
    @Optional
    public abstract Property<String> getPluginExportFile();

    @OutputFile
    public abstract RegularFileProperty getColorsXmlFile();

    @OutputFile
    @Optional
    public abstract RegularFileProperty getBindingsJsonFile();

    @TaskAction
    public void sync() throws Exception {
        String token = getToken().get();
        String fileKey = getFileKey().get();
        boolean extractTokens = getExtractTokens().getOrElse(false);
        boolean chainDownload = getChainDownload().getOrElse(false);
        List<String> collections = getCollections().getOrElse(Collections.emptyList());

        String tokenSource = getTokenSource().getOrElse("rest_api");

        Map<String, TokenClient.VariableInfo> variables;
        List<Map<String, Object>> pluginBindings = null;

        if ("plugin".equalsIgnoreCase(tokenSource)) {
            // ── Read from Figma plugin export JSON ────────────────
            String exportPath = getPluginExportFile().getOrElse(
                "src/main/assets/figma_plugin_export.json");
            File pluginFile = new File(getProject().getProjectDir(), exportPath);
            if (!pluginFile.exists()) {
                throw new RuntimeException("Plugin export file not found: " + pluginFile.getAbsolutePath()
                    + ". Export from Figma plugin first.");
            }
            getLogger().lifecycle("[Figma] Reading tokens from plugin export: {}", pluginFile.getPath());
            TokenClient.PluginExportData export = TokenClient.parsePluginExport(pluginFile);
            variables = export.tokens;
            pluginBindings = export.bindings;
            getLogger().lifecycle("[Figma] Plugin export: {} tokens, {} bindings from '{}'",
                variables.size(), pluginBindings != null ? pluginBindings.size() : 0,
                export.fileName);
        } else {
            // ── Fetch from REST API ───────────────────────────────
            getLogger().lifecycle("[Figma] Fetching design tokens (variables/local) ...");
            variables = TokenClient.fetchLocalVariablesFiltered(token, fileKey, collections, chainDownload);
        }

        if (tokenSource == null || !"plugin".equalsIgnoreCase(tokenSource)) {
            getLogger().lifecycle("[Figma] Found {} variables ({} color, {} other)",
                variables.size(),
                variables.values().stream().filter(v -> v.colorHex != null).count(),
                variables.values().stream().filter(v -> v.colorHex == null).count());
        }

        // ── Generate colors.xml ──────────────────────────────────
        File colorsFile = getColorsXmlFile().get().getAsFile();
        colorsFile.getParentFile().mkdirs();
        StringBuilder xml = new StringBuilder();
        xml.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\n");
        xml.append("<!-- Auto-generated by figma-sync-plugin. DO NOT EDIT. -->\n");
        xml.append("<resources>\n");

        int colorCount = 0;
        java.util.Set<String> usedNames = new java.util.HashSet<>();
        for (TokenClient.VariableInfo var : variables.values()) {
            if (var.colorHex == null) continue;
            String baseName = "figma_" + sanitizeResName(var.name);
            String resName = baseName;
            int dedupIdx = 1;
            while (usedNames.contains(resName)) {
                resName = baseName + "_" + (++dedupIdx);
            }
            usedNames.add(resName);
            xml.append("    <color name=\"").append(resName).append("\">")
               .append(var.colorHex).append("</color>\n");
            colorCount++;
        }
        xml.append("</resources>\n");

        java.nio.file.Files.write(colorsFile.toPath(),
            xml.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));
        getLogger().lifecycle("[Figma] Wrote {} colors → {}", colorCount, colorsFile.getPath());

        // ── Generate token_bindings.json ─────────────────────────
        File bindingsFile = getBindingsJsonFile().getOrNull() != null
            ? getBindingsJsonFile().get().getAsFile() : null;

        if (bindingsFile != null && extractTokens) {
            bindingsFile.getParentFile().mkdirs();
            List<Map<String, Object>> tokenList = new ArrayList<>();
            for (TokenClient.VariableInfo var : variables.values()) {
                if (var.colorHex == null) continue;
                Map<String, Object> entry = new LinkedHashMap<>();
                entry.put("name", var.name);
                entry.put("varId", var.id);
                entry.put("color", var.colorHex);
                tokenList.add(entry);
            }
            Map<String, Object> root = new LinkedHashMap<>();
            root.put("source", "rest_api".equalsIgnoreCase(tokenSource) ? "figma_variables_api" : "figma_plugin");
            root.put("count", tokenList.size());
            root.put("tokens", tokenList);
            if (pluginBindings != null && !pluginBindings.isEmpty()) {
                root.put("bindings", pluginBindings);
                root.put("bindingsCount", pluginBindings.size());
            }

            java.nio.file.Files.write(bindingsFile.toPath(),
                JsonOutput.toJson(root).getBytes(java.nio.charset.StandardCharsets.UTF_8));
            getLogger().lifecycle("[Figma] Wrote token bindings → {}", bindingsFile.getPath());
        }
    }

    static String sanitizeResName(String name) {
        return name.toLowerCase()
            .replaceAll("[^a-z0-9_]", "_")
            .replaceAll("_+", "_")
            .replaceAll("^_|_$", "");
    }
}
