#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────
# Figma Change Summary Generator
#
# Compares pre/post sync state and outputs a markdown change report
# for the automated PR body.
#
# Usage: bash figma-change-summary.sh <prev_version> <new_version> <prev_count> <new_count>
# ──────────────────────────────────────────────────────────────────
set -euo pipefail

PREV_VERSION="${1:-none}"
NEW_VERSION="${2:-none}"
PREV_COUNT="${3:-0}"
NEW_COUNT="${4:-0}"

NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

cat <<HEADER
## Figma Sync Summary

| Item | Before | After |
|------|--------|-------|
| Figma version | \`${PREV_VERSION}\` | \`${NEW_VERSION}\` |
| Asset count | ${PREV_COUNT} | ${NEW_COUNT} |
| Sync time | — | ${NOW} |

HEADER

# ── Changed files ────────────────────────────────────────────────
echo "### Changed Files"
echo
echo '```'
if command -v git &>/dev/null; then
    git diff --stat HEAD 2>/dev/null || echo "(no git changes detected)"
else
    echo "(git not available)"
fi
echo '```'

# ── Detailed diff for drawables ──────────────────────────────────
echo
echo "### Drawable Changes"
echo

ADDED=$(git diff --name-only --diff-filter=A HEAD 2>/dev/null | grep -E 'drawable.*\.xml$' | sed 's/.*\///' | sed 's/\.xml$//' || true)
MODIFIED=$(git diff --name-only --diff-filter=M HEAD 2>/dev/null | grep -E 'drawable.*\.xml$' | sed 's/.*\///' | sed 's/\.xml$//' || true)
DELETED=$(git diff --name-only --diff-filter=D HEAD 2>/dev/null | grep -E 'drawable.*\.xml$' | sed 's/.*\///' | sed 's/\.xml$//' || true)

if [ -n "$ADDED" ]; then
    echo "**Added:**"
    echo "$ADDED" | while read -r icon; do echo "- \`$icon\`"; done
    echo
fi

if [ -n "$MODIFIED" ]; then
    echo "**Modified:**"
    echo "$MODIFIED" | while read -r icon; do echo "- \`$icon\`"; done
    echo
fi

if [ -n "$DELETED" ]; then
    echo "**Removed:**"
    echo "$DELETED" | while read -r icon; do echo "- \`$icon\`"; done
    echo
fi

if [ -z "$ADDED" ] && [ -z "$MODIFIED" ] && [ -z "$DELETED" ]; then
    echo "_No drawable changes._"
fi

# ── Token changes ────────────────────────────────────────────────
echo
echo "### Token (Color) Changes"
echo

COLORS_DIFF=$(git diff HEAD -- app/src/main/res/values/figma_colors.xml 2>/dev/null | grep -E '^[+-]' | grep -v '^[+-][+-][+-]' | head -40 || true)
if [ -n "$COLORS_DIFF" ]; then
    echo '```diff'
    echo "$COLORS_DIFF"
    echo '```'
else
    echo "_No color token changes._"
fi

# ── Footer ───────────────────────────────────────────────────────
echo
echo "---"
echo "_Auto-generated by [Figma Sync CI](https://github.com/${GITHUB_REPOSITORY:-owner/repo}/actions/workflows/figma-sync.yml)._"
